# Generated by Django 3.1.1 on 2021-03-04 07:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='additional_cost',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='additional_value',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='comments',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='invoice/'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 4, 7, 7, 31, 678532, tzinfo=utc)),
        ),
    ]
