# Generated by Django 3.1.1 on 2021-03-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layerheight',
            old_name='value',
            new_name='end_value',
        ),
        migrations.AddField(
            model_name='layerheight',
            name='start_value',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
