# Generated by Django 3.1.1 on 2020-12-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201227_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='payment_method',
            field=models.IntegerField(blank=True, choices=[(0, 'Full Payment'), (1, 'Per Class Payment'), (2, 'Free Trail')], default=None, null=True),
        ),
    ]
