# Generated by Django 3.1.1 on 2021-03-02 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210302_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.material')),
            ],
        ),
    ]
