# Generated by Django 3.1.1 on 2021-03-04 07:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210304_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(0, 'Completed'), (1, 'Cancelled'), (2, 'Quoted'), (3, 'Pending'), (4, 'Payed'), (5, 'Shipped')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 4, 7, 58, 44, 721150, tzinfo=utc)),
        ),
    ]
