# Generated by Django 3.1.1 on 2021-03-04 08:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210304_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='invoice',
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_file_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 4, 8, 47, 29, 527944, tzinfo=utc)),
        ),
    ]
