# Generated by Django 3.1.1 on 2020-12-23 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_coursematerial_studentattendance_studentinstructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentattendance',
            name='student',
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='description',
            field=models.CharField(default='test', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='name',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='student_instructor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.studentinstructor'),
            preserve_default=False,
        ),
    ]
