# Generated by Django 3.1 on 2020-09-02 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_exam_examgrade_project_projectsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='country',
            field=models.CharField(choices=[('US', 'United States'), ('IN', 'India')], default='US', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('E', '1-5'), ('M', '6-8'), ('H', '9-12')], default='H', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='parents_name',
            field=models.CharField(default='Parent', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default='555-555-5555', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='courses', to='api.Student'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='api.course'),
        ),
        migrations.AlterField(
            model_name='examgrade',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='api.exam'),
        ),
        migrations.AlterField(
            model_name='examgrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_grades', to='api.student'),
        ),
        migrations.AlterField(
            model_name='project',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.course'),
        ),
        migrations.AlterField(
            model_name='projectsubmission',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api.project'),
        ),
        migrations.AlterField(
            model_name='projectsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_submissions', to='api.student'),
        ),
    ]
