# Generated by Django 3.1.1 on 2020-12-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201223_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='description',
            field=models.CharField(default='test', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='test', max_length=512),
            preserve_default=False,
        ),
    ]
