# Generated by Django 3.1 on 2020-09-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200902_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='grade',
            field=models.CharField(choices=[('E', '1-5'), ('M', '6-8'), ('H', '9-12')], default='H', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
