# Generated by Django 3.1.1 on 2021-03-03 12:20

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customerproductcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='customer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='stl_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='stl/', validators=[api.models.validate_file_extension]),
        ),
        migrations.DeleteModel(
            name='CustomerProductCart',
        ),
    ]
