# Generated by Django 3.1 on 2020-09-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200902_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsubmission',
            name='path',
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='file',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
