# Generated by Django 3.1.1 on 2020-12-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201224_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
