# Generated by Django 3.1.1 on 2021-01-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210102_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='is_tz_set',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_tz_set',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
