# Generated by Django 3.1.1 on 2020-12-24 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201224_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=[(0, 'PRESENT'), (1, 'ABSENT'), (2, 'OTHER')]),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.instructor'),
        ),
        migrations.DeleteModel(
            name='StudentAttendance',
        ),
    ]
