# Generated by Django 3.1 on 2020-09-21 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200920_0605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parents_name',
        ),
        migrations.AddField(
            model_name='student',
            name='parent_first_name',
            field=models.CharField(default='Parent', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='parent_last_name',
            field=models.CharField(default='Parent', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_first_name',
            field=models.CharField(default='Student', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_last_name',
            field=models.CharField(default='Student', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course'),
        ),
        migrations.AlterField(
            model_name='examgrade',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exam'),
        ),
        migrations.AlterField(
            model_name='examgrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
        migrations.AlterField(
            model_name='project',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course'),
        ),
        migrations.AlterField(
            model_name='projectsubmission',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
        migrations.AlterField(
            model_name='projectsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
    ]
