# Generated by Django 3.1.1 on 2020-12-25 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201224_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='price_usd',
            new_name='total_price_usd',
        ),
        migrations.AddField(
            model_name='course',
            name='per_class_price_usd',
            field=models.PositiveSmallIntegerField(default=5, help_text='Price in dollars'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'PRESENT'), (1, 'ABSENT'), (2, 'OTHER')], default=None, null=True),
        ),
        migrations.CreateModel(
            name='PaymentLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.IntegerField(choices=[(0, 'Full Payment'), (1, 'Per Class Payment')])),
                ('total_amount', models.PositiveSmallIntegerField(help_text='Price in usd')),
                ('amount_paid', models.PositiveSmallIntegerField(help_text='Price in usd')),
                ('amount_remaining', models.PositiveSmallIntegerField(help_text='Price in usd')),
                ('last_updated', models.DateTimeField()),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.enrollment')),
            ],
        ),
    ]
