# Generated by Django 3.1 on 2020-09-23 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200921_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='highlights',
            field=models.TextField(default='', help_text='Put each item on its own line'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.TextField(default='', help_text='Put each item on its own line'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='sessions',
            field=models.TextField(default='', help_text='Put each item on its own line'),
            preserve_default=False,
        ),
    ]
