# Generated by Django 3.1.1 on 2020-12-25 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201225_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='amount_paid',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='Price in usd', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='amount_remaining',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='Price in usd', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='enrollment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.enrollment'),
        ),
        migrations.AddField(
            model_name='event',
            name='payment_method',
            field=models.IntegerField(blank=True, choices=[(0, 'Full Payment'), (1, 'Per Class Payment')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='total_amount',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='Price in usd', null=True),
        ),
        migrations.DeleteModel(
            name='PaymentLedger',
        ),
    ]
