# Generated by Django 3.1.1 on 2021-01-03 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210102_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_link',
        ),
        migrations.AddField(
            model_name='exam',
            name='uploader',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.instructor'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='class_link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='uploader',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.instructor'),
        ),
    ]
