# Generated by Django 3.1.1 on 2020-12-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20201225_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='amount_remaining',
        ),
        migrations.AddField(
            model_name='event',
            name='paid_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
