# Generated by Django 3.1.1 on 2021-01-03 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210103_1754'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentinstructor',
            unique_together={('enrollment', 'instructor')},
        ),
    ]
