# Generated by Django 3.1.1 on 2020-12-26 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20201225_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='purchase',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='api.purchase'),
            preserve_default=False,
        ),
    ]
