# Generated by Django 3.1 on 2020-09-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='country',
            field=models.CharField(choices=[('1', 'United States'), ('98', 'India')], max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
