# Generated by Django 3.1.1 on 2020-12-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_enrollment_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examgrade',
            old_name='grade',
            new_name='marks',
        ),
        migrations.RemoveField(
            model_name='projectsubmission',
            name='file',
        ),
        migrations.AddField(
            model_name='exam',
            name='file_link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='file_link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
