# Generated by Django 3.1 on 2020-09-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200923_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='country',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
