# Generated by Django 3.1.1 on 2020-12-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20201226_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='assignments',
            field=models.TextField(default='test', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='exams',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(max_length=512),
        ),
    ]
