# Generated by Django 3.1.1 on 2020-12-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20201226_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='thumbnail/'),
        ),
    ]
