# Generated by Django 3.1 on 2020-10-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='confirmed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
