# Generated by Django 3.1 on 2020-10-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_purchase_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='stripe_id',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
