# Generated by Django 3.1 on 2020-10-14 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_purchase_stripe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
