# Generated by Django 3.1.1 on 2020-12-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20201216_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabledays',
            name='day',
            field=models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], unique=True),
        ),
    ]
